[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
test = "test"
script = "script"
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false
fs_permissions = []

[profile.default.invariant]
runs = 256
depth = 32
fail_on_revert = false

[rpc_endpoints]
robinhood_mainnet = "https://rpc.mainnet.chain.robinhood.com"
robinhood_testnet = "${ROBINHOOD_TESTNET_RPC_URL}"

[etherscan]
robinhood_mainnet = { key = "${BLOCKSCOUT_API_KEY}", url = "https://robinhoodchain.blockscout.com/api", chain = 4663 }
