// Regenerates src/lib/web3/abi/index.ts from the Foundry ABI exports in the same
// folder. JSON imports cannot be `as const`, so this emits literal arrays that give
// wagmi/viem full type inference. Run: node scripts/generate-abi-ts.mjs
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const dir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "lib", "web3", "abi");
const files = readdirSync(dir).filter((f) => f.endsWith(".json")).sort();
const camel = (s) => s[0].toLowerCase() + s.slice(1);
let out = "// GENERATED by scripts/generate-abi-ts.mjs from the Foundry ABI JSON in this folder. Do not edit.\n\n";
for (const f of files) {
  const name = f.replace(/\.json$/, "");
  const abi = JSON.parse(readFileSync(join(dir, f), "utf8"));
  const clean = abi.map((item) => {
    const strip = (p) => ({ ...p, internalType: undefined, components: p.components?.map(strip) });
    const drop = (o) => JSON.parse(JSON.stringify(o));
    return drop({ ...item, inputs: item.inputs?.map(strip), outputs: item.outputs?.map(strip) });
  });
  out += `export const ${camel(name)}Abi = ${JSON.stringify(clean)} as const;\n\n`;
}
writeFileSync(join(dir, "index.ts"), out);
console.log(`wrote ${files.length} ABIs to ${join(dir, "index.ts")}`);
